import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
page.on('pageerror',error=>errors.push(error.message));
const url=process.env.BASE_URL||'http://localhost:3000';
await page.goto(url,{waitUntil:'networkidle'});
await mkdir('test-results',{recursive:true});
assert.equal(await page.locator('html').getAttribute('lang'),'th');
assert.match(await page.locator('.hero-description').innerText(),/ผมทำหุ่นยนต์/);
assert.equal(await page.locator('img[src*="-photo.png"]').count(),0,'Generated photos are no longer shown');
assert.equal(await page.locator('.hero .board-float svg').count(),1);
await page.setViewportSize({width:390,height:844});
const pidCard=page.locator('a.project-card[href="/pid-lab"]');
await pidCard.scrollIntoViewIfNeeded();
assert.equal(await pidCard.evaluate(el=>getComputedStyle(el).display),'block','PID Lab link must remain a full card inside the Ant Design column');
assert.ok((await pidCard.boundingBox()).width>=340,'PID Lab card fills the mobile column');
await page.setViewportSize({width:1440,height:1000});
await page.locator('select').selectOption('en');
assert.match(await page.locator('.hero-description').innerText(),/I build robots/);
assert.equal(await page.getByRole('link',{name:'GitHub profile'}).first().getAttribute('href'),'https://github.com/ttwatchesyou');
await page.getByRole('button',{name:'View all 19 projects'}).click();
assert.equal(await page.locator('.project-card').count(),19);
await page.getByRole('button',{name:'Robotics',exact:true}).click();
assert.equal(await page.locator('.project-card').count(),4);
await page.getByRole('button',{name:'View National Robotics Competition'}).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.locator('.project-role').innerText(),/Designed, built/);
await page.getByRole('button',{name:'Back to projects'}).click();
await page.getByRole('button',{name:'Automation & PLC',exact:true}).click();
await page.getByRole('button',{name:'View WorldSkills Thailand Preparation'}).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.locator('.project-role').innerText(),/Practiced/);
await page.getByRole('button',{name:'Back to projects'}).click();
await page.getByRole('button',{name:/All projects/}).click();
await page.getByRole('button',{name:'Run initialization sequence'}).click();
await page.waitForFunction(()=>document.querySelectorAll('.terminal-body .ok').length===4);
await page.locator('.nav-contact').click();
await page.getByRole('button',{name:'Create message draft'}).click();
await page.getByText('Please enter your name.',{exact:true}).waitFor();
await page.getByLabel('Your name',{exact:true}).fill('Visitor');
await page.getByLabel('Email',{exact:true}).fill('maker@example.com');
await page.getByLabel('Your message or idea').fill('Build a connected robot.');
await page.getByRole('button',{name:'Create message draft'}).click();
assert.match(await page.locator('.draft-result').innerText(),/Build a connected robot/);
await page.locator('.ant-modal-close').click();
await page.getByRole('dialog').waitFor({state:'hidden'});
const model=page.locator('.board-model');
await page.locator('#workbench').scrollIntoViewIfNeeded();
await page.locator('.board-model[data-renderer="ready"]').waitFor();
assert.ok(Number(await model.getAttribute('data-part-count'))>=100);
const waitPose=async(exploded)=>page.waitForFunction(flag=>{const n=Number(document.querySelector('.board-model')?.dataset.renderedSpread);return flag?n>.995:n<.005;},exploded,{timeout:15000});
const scrollAssembly=async(progress)=>{await page.locator('#workbench').evaluate((host,p)=>{const sticky=host.querySelector('.assembly-sticky');window.dispatchEvent(new WheelEvent('wheel'));scrollTo({top:scrollY+host.getBoundingClientRect().top-parseFloat(getComputedStyle(sticky).top)+p*(host.offsetHeight-sticky.offsetHeight),behavior:'instant'});},progress);};
await scrollAssembly(0);await waitPose(false);
const assembled=await page.locator('.board-model canvas').screenshot();
await scrollAssembly(.5);await waitPose(true);
const exploded=await page.locator('.board-model canvas').screenshot();
assert.ok(!assembled.equals(exploded),'The rendered canvas changes, not just the stage label');
await page.locator('.assembly-sticky').screenshot({path:'test-results/assembly-exploded.png'});
await scrollAssembly(1);await waitPose(false);
await scrollAssembly(.5);await waitPose(true);
await scrollAssembly(0);await waitPose(false);
// Stage buttons must stay selected even when browser scrolling brings them into view.
await page.locator('.assembly-tabs button').nth(1).click();await waitPose(true);
await page.locator('.assembly-tabs button').nth(2).click();await waitPose(false);
await page.getByRole('slider',{name:'Assembly timeline'}).fill('50');await waitPose(true);
await page.getByRole('button',{name:'Zoom board details'}).click();assert.equal(await page.getByRole('button',{name:'Zoom board details'}).getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'Zoom board details'}).click();
await page.getByRole('button',{name:'Wireframe',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Wireframe',exact:true}).getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'Wireframe',exact:true}).click();
await page.getByRole('button',{name:'▶ Play assembly'}).click();
await page.waitForFunction(()=>Number(document.querySelector('.board-model')?.dataset.renderedSpread)>.85,null,{timeout:15000});
await page.getByRole('button',{name:'▶ Play assembly'}).waitFor({timeout:15000});await waitPose(false);
assert.equal(await page.locator('.board-model canvas').getAttribute('style'),null);
await page.getByRole('slider',{name:'Motor speed'}).fill('80');
assert.equal(await page.getByTestId('motor-rpm').innerText(),'4800');
await page.getByRole('button',{name:'Reverse direction'}).click();
assert.equal(await page.getByRole('button',{name:'Reverse direction'}).getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'Sensor trigger'}).click();assert.match(await page.locator('.lab-state').innerText(),/Signal received/);
await page.getByRole('button',{name:'Power off',exact:true}).click();assert.equal(await page.getByTestId('motor-rpm').innerText(),'0');
await page.getByRole('button',{name:'Power on',exact:true}).click();
await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
const visual=await page.locator('.hero .visual').boundingBox();await page.mouse.move(visual.x+30,visual.y+60);await page.waitForTimeout(200);
const first=await page.locator('.board-response').evaluate(el=>getComputedStyle(el).transform);await page.mouse.move(visual.x+visual.width-30,visual.y+visual.height-60);await page.waitForTimeout(200);
assert.notEqual(await page.locator('.board-response').evaluate(el=>getComputedStyle(el).transform),first);
await page.screenshot({path:'test-results/hero-motion.png'});
await page.locator('.skill-card').first().scrollIntoViewIfNeeded();await page.waitForTimeout(650);
for(const locale of ['th','zh','en']){
 await page.locator('select').selectOption(locale);
 assert.equal(await page.locator('html').getAttribute('lang'),locale==='zh'?'zh-CN':locale);
 assert.ok(await page.locator('.skill-card').first().evaluate(el=>getComputedStyle(el).opacity!=='0'),'Translated skills remain visible');
 for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${locale} overflows at ${width}`);}
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`test-results/language-${locale}.png`});
}
await page.locator('select').selectOption('zh');await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');
await page.locator('button.project-card').first().click();await page.getByRole('dialog').waitFor();assert.match(await page.locator('.project-role').innerText(),/设计/);await page.locator('.ant-modal-close').click();await page.getByRole('dialog').waitFor({state:'hidden'});
await page.setViewportSize({width:390,height:844});await page.locator('#workbench').scrollIntoViewIfNeeded();await page.locator('.board-model[data-renderer="ready"]').waitFor();await page.locator('.assembly-tabs button').nth(1).click();await waitPose(true);await page.screenshot({path:'test-results/assembly-mobile.png'});
await page.getByRole('button',{name:'打开菜单'}).click();await page.getByRole('link',{name:'作品',exact:true}).click();assert.equal(await page.getByRole('button',{name:'打开菜单'}).getAttribute('aria-expanded'),'false');
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.body.dataset.effects==='off');await page.locator('.assembly-tabs button').nth(1).click();await waitPose(true);
assert.equal(await page.locator('.assembly-play').count(),0);
const fallback=await browser.newPage({reducedMotion:'reduce'});
await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind.startsWith('webgl')?null:original.call(this,kind,...args);};});
await fallback.goto(url,{waitUntil:'networkidle'});await fallback.locator('#workbench').scrollIntoViewIfNeeded();await fallback.locator('.board-model[data-renderer="unavailable"]').waitFor();await fallback.locator('.assembly-tabs button').nth(1).click();assert.equal(await fallback.locator('.board-model').getAttribute('data-spread'),'true');assert.ok(await fallback.locator('.model-fallback svg').isVisible());
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: restored vectors; 105 independent parts; actual canvas separation/reassembly; scroll both ways; buttons, scrubber, demo, zoom, wireframe; interactive signal lab; TH/ZH/EN + persistence; translated project details; forms; pointer tilt; 15 responsive combinations; reduced motion; WebGL fallback.');
