'use client';
import styled from 'styled-components';

export const Notebook = styled.div`
  min-height:100vh;overflow:clip;
  .book-wrap{max-width:1280px;margin:auto;padding:0 48px;}
  .book-header{position:sticky;top:0;z-index:15;background:var(--nav);backdrop-filter:blur(18px);border-bottom:1px solid var(--border);}
  .header-inner{min-height:84px;display:flex;align-items:center;justify-content:space-between;gap:24px;}
  .book-brand{font-size:19px;font-weight:800;letter-spacing:-.7px;}.book-brand span{color:var(--accent);}
  .expanded-study{margin-top:35px;padding-top:28px;border-top:1px solid var(--border);}.expanded-study h3{margin:27px 0 12px;font-size:15px;font-weight:600;color:var(--accent);}.expanded-study p,.evaluation-list{font-size:13px;line-height:1.95;color:var(--muted);}.expanded-study .editorial-note{font-size:11px;border-left:2px solid var(--warm);padding-left:15px;}.evaluation-list{padding-left:20px;}.evaluation-list li{padding:7px 0;}.expanded-study .source-links h3{margin-bottom:0;}
  .header-tools{display:flex;align-items:center;gap:12px;}.home-link{font-size:11px;color:var(--muted);min-height:44px;display:flex;align-items:center;gap:8px;}
  .book-label{font:10px var(--mono);letter-spacing:1.6px;color:var(--accent);display:flex;align-items:center;gap:12px;}.book-label:before{content:'';width:27px;height:1px;background:currentColor;}
  .book-hero{padding:65px 0 55px;display:grid;grid-template-columns:1.15fr .85fr;gap:60px;align-items:center;border-bottom:1px solid var(--border);}
  h1{white-space:pre-line;font-size:clamp(34px,4.3vw,60px);line-height:1.25;font-weight:550;letter-spacing:-1.7px;margin:24px 0;overflow-wrap:anywhere;}
  .intro{font-size:14px;line-height:1.95;color:var(--muted);max-width:500px;}.hero-count{display:flex;align-items:center;gap:18px;margin-top:28px;}.hero-count strong{font:47px var(--mono);font-weight:400;color:var(--warm);}.hero-count span{max-width:240px;color:var(--muted);font-size:11px;line-height:1.9;}
  .desk-photo{margin:0;position:relative;border:1px solid var(--border);padding:10px;background:var(--surface);transform:rotate(1.2deg);box-shadow:0 14px 35px #00000012;}.desk-photo img{display:block;width:100%;height:295px;object-fit:cover;object-position:center 60%;}.desk-photo figcaption{font-size:10px;line-height:1.8;color:var(--muted);padding:13px 5px 4px;}.desk-photo:after{content:'WORKBENCH / FIELD NOTES';position:absolute;top:23px;left:23px;background:#182c27e8;color:#fff;padding:7px 9px;font:8px var(--mono);letter-spacing:.9px;}
  .browse{padding:40px 0 70px;}.browse-head{display:flex;gap:20px;justify-content:space-between;align-items:center;margin-bottom:24px;}.search{width:370px;max-width:100%;}.search input{min-height:32px;}.result-count{font:11px var(--mono);color:var(--muted);}
  .filters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:30px;}.filters button{padding:11px 16px;min-height:44px;border:1px solid var(--border);border-radius:30px;background:var(--surface);color:var(--muted);font-size:11px;}.filters button[aria-pressed='true']{background:var(--accent);color:var(--bg);border-color:var(--accent);}
  .book-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;}.entry{min-width:0;border:1px solid var(--border);border-radius:7px;background:var(--surface);overflow:hidden;transition:transform .3s,box-shadow .3s;}.entry:focus-visible{outline:2px solid var(--accent);outline-offset:4px;}.entry-visual{position:relative;aspect-ratio:400/270;background:var(--bg);border-bottom:1px solid var(--border);}.entry-visual svg{transition:transform .4s;}.entry-number{position:absolute;top:16px;left:16px;font:10px var(--mono);color:var(--muted);}.entry-concept{position:absolute;bottom:10px;right:12px;font-size:9px;color:var(--muted);background:var(--surface);padding:4px 7px;border-radius:3px;}
  .entry-body{padding:23px;}.entry-group{font-size:10px;color:var(--accent);}.entry h2{font-size:19px;line-height:1.55;font-weight:600;margin:10px 0;}.entry p{font-size:12px;line-height:1.85;color:var(--muted);margin:0 0 18px;}.entry-tags{display:flex;gap:6px;flex-wrap:wrap;}.entry-tags span{font:9px var(--mono);padding:5px 7px;border:1px solid var(--border);border-radius:3px;color:var(--muted);}.entry-open{margin-top:21px;padding-top:16px;border-top:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;font-size:11px;color:var(--accent);}
  @media(hover:hover){.entry:hover{transform:translateY(-5px);box-shadow:0 12px 28px #00000012;}.entry:hover .entry-visual svg{transform:scale(1.025);}}
  .empty{padding:45px 20px;text-align:center;color:var(--muted);font-size:14px;line-height:1.9;}.empty button{margin-top:12px;}
  .book-footer{padding:25px 0;border-top:1px solid var(--border);color:var(--muted);font-size:11px;}.footer-inner{display:flex;justify-content:space-between;gap:20px;line-height:1.8;}
  .breadcrumbs{padding-top:28px;display:flex;gap:10px;align-items:center;font-size:11px;color:var(--muted);}.breadcrumbs a{min-height:44px;display:flex;align-items:center;}
  .detail-hero{display:grid;grid-template-columns:1fr 1fr;gap:50px;padding:38px 0 50px;align-items:center;}.detail-hero h1{font-size:clamp(32px,3.5vw,48px);margin-top:20px;}.detail-summary{font-size:14px;line-height:1.95;color:var(--muted);}.detail-art{border:1px solid var(--border);border-radius:8px;background:var(--surface);overflow:hidden;}.detail-art .drawing{aspect-ratio:400/270;}.art-caption{padding:15px 20px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-top:1px solid var(--border);font-size:10px;color:var(--muted);}.art-caption button{min-height:44px;padding:8px 12px;color:var(--accent);border:1px solid var(--border);border-radius:4px;background:var(--bg);font-size:10px;}
  .photo-pending{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:11px;margin-top:20px;}.photo-pending span{width:6px;height:6px;border-radius:50%;background:var(--warm);}
  .detail-content{display:grid;grid-template-columns:1.3fr .7fr;gap:40px;padding:15px 0 65px;}.note-panel{border-top:1px solid var(--border);padding-top:24px;}.note-panel h2{font-size:23px;font-weight:550;margin:0 0 22px;}.component-list{list-style:none;padding:0;margin:0;}.component-list li{display:flex;gap:19px;padding:19px 0;border-bottom:1px solid var(--border);line-height:1.85;font-size:13px;}.component-list .list-number{font:12px var(--mono);color:var(--warm);padding-top:5px;}
  .note-callout{padding:24px;border:1px solid var(--border);border-radius:5px;background:var(--surface);}.note-callout h2{font-size:19px;}.note-callout p,.method p{font-size:13px;line-height:1.95;color:var(--muted);}.source-links{display:flex;flex-direction:column;align-items:start;gap:10px;margin-top:17px;}.source-links a{min-height:44px;font-size:12px;color:var(--accent);display:flex;align-items:center;gap:8px;text-decoration:underline;text-underline-offset:4px;}.source-notes{margin-top:22px;border-top:1px solid var(--border);padding-top:17px;}.source-notes summary{cursor:pointer;min-height:44px;font-size:12px;color:var(--accent);}.source-notes pre{white-space:pre-wrap;overflow-wrap:anywhere;font-family:inherit;font-size:12px;color:var(--muted);line-height:1.9;margin:0;}.method{margin-top:35px;}.related-lab{display:block;border:1px solid var(--border);padding:20px;border-radius:5px;margin-top:22px;background:var(--surface);}.related-lab strong{color:var(--accent);font-size:13px;}.related-lab p{margin-bottom:0;font-size:11px;}
  .entry-nav{display:grid;grid-template-columns:1fr 1fr;gap:24px;padding-bottom:60px;}.entry-nav a{border-top:1px solid var(--border);padding-top:22px;min-width:0;}.entry-nav span{font-size:11px;color:var(--muted);}.entry-nav h3{font-size:17px;font-weight:550;line-height:1.7;}.entry-nav a:last-child{text-align:right;}
  @media(max-width:1000px){.book-wrap{padding:0 28px;}.book-hero{gap:30px;}.book-grid{grid-template-columns:repeat(2,minmax(0,1fr));}.detail-hero{gap:30px;}.header-tools{gap:8px;}}
  @media(max-width:700px){.book-wrap{padding:0 20px;}.header-inner{min-height:100px;flex-wrap:wrap;gap:8px;padding-block:13px;}.book-brand{font-size:17px;}.home-link{display:none;}.header-tools{margin-left:auto;}.book-hero{grid-template-columns:1fr;padding:39px 0;gap:28px;}h1{letter-spacing:-.9px;}.desk-photo{transform:none;}.desk-photo img{height:240px;}.book-grid{grid-template-columns:1fr;gap:20px;}.browse-head{align-items:start;flex-direction:column;gap:15px;}.search{width:100%;}.filters button{padding:10px 13px;}.detail-hero,.detail-content{grid-template-columns:1fr;gap:28px;}.detail-hero{padding-top:22px;}.detail-content{padding-bottom:40px;}.detail-art{max-width:100%;}.entry-nav{gap:20px;}.entry-nav h3{font-size:14px;}.footer-inner{flex-direction:column;gap:5px;}.art-caption{flex-wrap:wrap;}}
  @media(prefers-reduced-motion:reduce){.entry,.entry-visual svg{transition:none;}.entry:hover,.entry:hover .entry-visual svg{transform:none;}}
`;
