'use client';
import styled from 'styled-components';
export const LabShell=styled.div`
  .scene-drive{position:absolute;right:20px;bottom:14px;display:grid;grid-template-columns:1fr auto;gap:4px 8px;pointer-events:none;font:9px var(--mono);color:var(--accent);min-width:125px;}.scene-drive span{color:var(--muted);font-family:Manrope,Arial,sans-serif;}.scene-drive strong{font-weight:500;}.scene-drive svg{grid-column:1/-1;width:100%;}.scene-drive[data-limited='true']{color:var(--warm);}.scene-drive[data-failed='true']{color:#c57167;}
  min-height:100vh;background:var(--bg);color:var(--text);overflow:clip;
  .lab-wrap{width:min(1400px,100% - 80px);margin:auto;}
  .lab-nav{border-bottom:1px solid var(--border);background:var(--nav);backdrop-filter:blur(14px);position:sticky;top:0;z-index:30;}
  .lab-nav-inner{height:76px;display:flex;align-items:center;justify-content:space-between;gap:20px;}
  .lab-brand{font-size:17px;letter-spacing:-.6px;font-weight:700;display:flex;align-items:center;gap:14px;}.lab-brand span{border-left:1px solid var(--border);padding-left:14px;font:11px var(--mono);letter-spacing:1px;color:var(--muted);}
  .nav-tools{display:flex;align-items:center;gap:10px;}.back-link{font-size:11px;color:var(--muted);margin-right:16px;}
  .lab-intro{padding:42px 0 26px;display:flex;align-items:end;justify-content:space-between;gap:30px;}
  .kicker{font:10px var(--mono);letter-spacing:1.5px;color:var(--accent);display:flex;align-items:center;gap:8px;}.kicker::before{content:'';width:6px;height:6px;border-radius:50%;background:var(--accent);}
  h1{font-size:clamp(36px,4.2vw,56px);letter-spacing:-2px;font-weight:600;line-height:1.15;margin:14px 0 12px;}h1 em{font-family:Georgia,serif;font-weight:400;color:var(--warm);}
  .intro-copy{max-width:650px;font-size:13px;line-height:1.85;color:var(--muted);margin:0;}.intro-tag{font:10px var(--mono);padding:10px 13px;border:1px solid var(--border);border-radius:4px;color:var(--muted);white-space:nowrap;}
  .plant-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:26px;}
  .plant-tab{background:var(--surface);border:1px solid var(--border);border-radius:9px;padding:19px;display:flex;align-items:center;gap:14px;color:var(--text);text-align:left;transition:transform .2s,border .2s;min-width:0;}
  .plant-tab:hover{transform:translateY(-2px);}.plant-tab[aria-selected='true']{border-color:var(--accent);box-shadow:inset 0 -3px var(--accent);background:var(--surface-strong);}
  .plant-tab svg{width:46px;height:46px;flex-shrink:0;color:var(--accent);}.plant-tab strong{font-size:14px;font-weight:600;display:block;margin:4px 0;}.plant-tab small{font:9px var(--mono);color:var(--muted);}.plant-tab .plant-arrow{margin-left:auto;color:var(--accent);font-size:20px;}
  .workspace{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:22px;align-items:start;margin-bottom:30px;}.lab-main{min-width:0;display:grid;gap:18px;}
  .panel{background:var(--surface);border:1px solid var(--border);border-radius:10px;overflow:hidden;}.panel-head{padding:16px 20px;display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid var(--border);}.panel-head h2,.panel-head h3{font-size:13px;font-weight:600;margin:0;}.panel-head small{font:9px var(--mono);color:var(--muted);}.panel-number{font:10px var(--mono);color:var(--warm);margin-right:8px;}
  .model-scene{height:355px;position:relative;background:radial-gradient(ellipse at center,var(--surface-strong),var(--surface));}.model-scene canvas{display:block;width:100%;height:100%;touch-action:pan-y;}.model-scene[data-draggable='true']{cursor:grab;touch-action:none;user-select:none;}.model-scene[data-draggable='true'][data-dragging='true']{cursor:grabbing;}.model-scene[data-draggable='true']:focus-visible{outline:2px solid var(--accent);outline-offset:-3px;}.model-scene[data-draggable='true'] canvas{touch-action:none;}.scene-label{position:absolute;left:20px;top:16px;pointer-events:none;font:9px var(--mono);color:var(--muted);}.scene-angle{position:absolute;right:20px;top:17px;text-align:right;pointer-events:none;font:10px var(--mono);color:var(--muted);}.scene-angle strong{font-size:27px;color:var(--accent);display:block;margin:5px 0;}.scene-legend{position:absolute;left:20px;bottom:15px;font-size:10px;color:var(--muted);display:flex;gap:15px;}.scene-legend span{display:flex;align-items:center;gap:6px;}.scene-legend i{width:15px;height:2px;background:var(--accent);}.scene-legend .target{background:var(--warm);}.scene-drag-hint{position:absolute;left:50%;bottom:14px;transform:translateX(-50%);pointer-events:none;border:1px solid var(--border);background:color-mix(in srgb,var(--surface) 86%,transparent);border-radius:999px;padding:5px 9px;font-size:9px;color:var(--muted);white-space:nowrap;}
  .model-fallback{position:absolute;inset:30px;}.model-fallback svg{width:100%;height:100%;}.model-unavailable{position:absolute;bottom:10px;right:15px;font-size:9px;color:var(--muted);}
  .model-scene{height:410px;}.scene-drag-hint{bottom:39px;max-width:calc(100% - 28px);white-space:normal;text-align:center;line-height:1.55;}.scene-view-controls{position:absolute;left:50%;top:13px;transform:translateX(-50%);}.scene-view-controls button{display:flex;align-items:center;gap:6px;padding:7px 10px;font-size:10px;background:color-mix(in srgb,var(--surface) 88%,transparent);border:1px solid var(--border);border-radius:5px;color:var(--muted);cursor:zoom-in;touch-action:manipulation;}.scene-view-controls button[aria-pressed='true']{cursor:zoom-out;color:var(--accent);border-color:var(--accent);}.scene-view-controls button:focus-visible{outline:2px solid var(--accent);outline-offset:3px;}
  .run-toolbar{padding:13px 18px;display:flex;align-items:center;gap:8px;flex-wrap:wrap;border-top:1px solid var(--border);}.clock{margin-left:auto;font:11px var(--mono);color:var(--muted);font-variant-numeric:tabular-nums;}.clock strong{color:var(--text);}
  .metrics{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--border);}.metric{padding:16px 18px;border-right:1px solid var(--border);min-width:0;}.metric:last-child{border:0;}.metric label{font-size:10px;color:var(--muted);display:block;margin-bottom:8px;}.metric strong{font-size:22px;font-weight:550;font-variant-numeric:tabular-nums;letter-spacing:-.5px;}.metric small{font:9px var(--mono);margin-left:5px;color:var(--muted);}
  .status{border:1px solid var(--border);border-left:3px solid var(--accent);padding:12px 15px;border-radius:5px;background:var(--surface);display:flex;gap:10px;align-items:start;}.status[data-level='warning']{border-left-color:var(--warm);}.status[data-level='error']{border-left-color:#c74d43;}.status strong{font-size:12px;display:block;margin-bottom:3px;}.status p{font-size:11px;line-height:1.8;margin:0;color:var(--muted);}.status-icon{font-size:17px;color:var(--warm);}
  .control-panel{position:sticky;top:94px;}.control-body{padding:18px;}.control-section+.control-section{border-top:1px solid var(--border);padding-top:18px;margin-top:18px;}.control-label{font-size:11px;color:var(--muted);display:flex;align-items:center;justify-content:space-between;margin:0 0 8px;}.control-row{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:15px 0;}.control-row .ant-input-number{width:100%;}.control-note{font-size:10px;color:var(--muted);line-height:1.8;margin:9px 0 0;}.command-button{width:100%;}.mode-toggle{display:flex;gap:4px;background:var(--bg);border-radius:5px;padding:4px;}.mode-toggle button{flex:1;border:0;border-radius:3px;background:transparent;color:var(--muted);padding:9px 5px;font-size:10px;}.mode-toggle button[aria-pressed='true']{background:var(--surface-strong);color:var(--text);box-shadow:0 1px 4px var(--shadow);}
  .preset-row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:18px;}.preset-row button{border:1px solid var(--border);border-radius:4px;background:var(--bg);padding:6px 9px;font-size:10px;color:var(--muted);}
  .gain-row{margin:0 0 15px;}.gain-top{display:flex;align-items:center;justify-content:space-between;gap:15px;}.gain-top label{display:flex;gap:8px;align-items:center;font:12px var(--mono);}.gain-top label small{font:10px 'Manrope',Arial,sans-serif;color:var(--muted);}.gain-top .ant-input-number{width:85px;}.gain-row input[type='range']{width:100%;accent-color:var(--accent);margin:10px 0 0;height:15px;cursor:ew-resize;}
  .term-readings{display:flex;gap:10px;justify-content:space-between;font:10px var(--mono);color:var(--muted);background:var(--bg);padding:10px;border-radius:4px;font-variant-numeric:tabular-nums;}
  details{border-top:1px solid var(--border);padding:14px 0 0;margin-top:15px;}summary{cursor:pointer;font-size:11px;font-weight:600;list-style-position:inside;}details p{font-size:11px;color:var(--muted);line-height:1.8;}.option-row{display:flex;justify-content:space-between;align-items:center;gap:10px;font-size:11px;margin:14px 0;}.system-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px;}.system-fields .ant-input-number{width:100%;}.system-fields label{font-size:10px;color:var(--muted);display:block;margin-bottom:6px;}
  .chart-panel .panel-head{border-bottom:0;}.chart-tools{display:flex;align-items:center;gap:12px;font-size:10px;}.chart-tools select{color:var(--text);background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:5px;font-size:10px;}.chart{padding:0 12px;position:relative;}.chart svg{width:100%;display:block;height:auto;touch-action:pan-y;}.chart-grid{stroke:var(--border);stroke-width:.65;}.chart-label{fill:var(--muted);font:10px var(--mono);}.chart-line{fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}.chart-actual{stroke:var(--accent);}.chart-target{stroke:var(--warm);stroke-dasharray:5 5;stroke-width:1.5;}.chart-baseline{stroke:var(--muted);stroke-dasharray:2 4;stroke-width:1.2;opacity:.7;}.chart-effort{stroke:var(--warm);}.chart-foot{display:flex;gap:14px;flex-wrap:wrap;align-items:center;padding:5px 20px 14px;font-size:10px;color:var(--muted);}.chart-foot span{display:flex;gap:5px;align-items:center;}.legend-line{width:14px;height:2px;background:var(--accent);}.legend-target{background:var(--warm);}.chart-value{margin-left:auto;font:9px var(--mono);font-variant-numeric:tabular-nums;}.chart-empty{fill:var(--muted);font:12px 'Manrope',Arial,sans-serif;}.chart-inspector{position:absolute;right:20px;top:3px;background:var(--surface);border:1px solid var(--border);border-radius:4px;padding:6px 9px;font:10px var(--mono);color:var(--text);pointer-events:none;box-shadow:0 3px 12px var(--shadow);}.chart-compare{display:flex;gap:8px;padding:0 20px 16px;flex-wrap:wrap;}.chart-mode{border:0;background:transparent;color:var(--muted);font-size:10px;padding:6px 0;}.chart-mode[aria-pressed='true']{color:var(--accent);font-weight:600;}
  .learning-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding:0 0 30px;}.learning-card{padding:22px;background:var(--surface);border:1px solid var(--border);border-radius:8px;}.learning-card h3{font-size:14px;font-weight:500;margin:10px 0;}.learning-card p{font-size:11px;line-height:1.9;color:var(--muted);margin:0;}.learning-card .step{font:10px var(--mono);color:var(--warm);}
  .model-notes{padding:0 0 30px;}.model-notes details{padding:20px;border:1px solid var(--border);border-radius:8px;background:var(--surface);margin:0;}.equations{font:12px var(--mono);white-space:pre-wrap;line-height:2;background:var(--bg);padding:16px;border-radius:6px;overflow-wrap:anywhere;}.source-links{display:flex;gap:15px;flex-wrap:wrap;font-size:11px;color:var(--accent);}.source-links a{text-decoration:underline;}
  .lab-footer{border-top:1px solid var(--border);padding:22px 0;font-size:10px;color:var(--muted);}.lab-footer .lab-wrap{display:flex;justify-content:space-between;gap:15px;}
  @media(max-width:1100px){.lab-wrap{width:calc(100% - 40px);}.workspace{grid-template-columns:minmax(0,1fr) 305px;gap:16px;}.plant-tab{padding:14px;}.plant-tab svg{width:34px;height:34px;}.plant-tab strong{font-size:12px;}.model-scene{height:360px;}.metric{padding:12px;}.metric strong{font-size:19px;}}
  @media(max-width:850px){.workspace{grid-template-columns:1fr;}.control-panel{position:static;}.control-body{display:grid;grid-template-columns:1fr 1fr;gap:22px;}.control-section+.control-section{margin:0;padding:0;border:0;}.control-section:last-child{grid-column:1/-1;}.lab-intro{align-items:start;}.intro-tag{display:none;}.model-scene{height:370px;}.learning-grid{gap:12px;}.learning-card{padding:16px;}}
  @media(max-width:560px){.lab-wrap{width:calc(100% - 28px);}.lab-nav-inner{height:64px;gap:8px;}.lab-brand{font-size:14px;gap:8px;}.lab-brand span{display:none;}.nav-tools{gap:6px;}.back-link{display:none;}.lab-intro{padding:26px 0 22px;}.intro-copy{font-size:12px;}.plant-tabs{gap:7px;margin-bottom:18px;}.plant-tab{display:block;padding:12px 9px;}.plant-tab svg{width:32px;height:32px;}.plant-tab small{font-size:8px;}.plant-tab strong{font-size:11px;line-height:1.6;}.plant-arrow{display:none;}.model-scene{height:300px;}.panel-head{padding:13px;}.panel-head h2{font-size:12px;}.metrics{grid-template-columns:repeat(2,1fr);}.metric:nth-child(2){border-right:0;}.metric:nth-child(-n+2){border-bottom:1px solid var(--border);}.metric strong{font-size:22px;}.run-toolbar{padding:12px;}.run-toolbar .ant-btn{font-size:11px;}.clock{font-size:10px;}.control-body{display:block;padding:16px;}.control-section+.control-section{padding-top:18px;margin-top:18px;border-top:1px solid var(--border);}.learning-grid{grid-template-columns:1fr;}.learning-card{padding:18px;}.scene-angle{right:13px;top:14px;}.scene-angle strong{font-size:23px;}.scene-label{font-size:7px;left:14px;}.scene-legend{font-size:8px;left:14px;}.chart-foot{padding-left:14px;padding-right:14px;font-size:9px;gap:10px;}.chart-value{margin-left:0;}.lab-footer .lab-wrap{flex-direction:column;}.chart-compare{padding-left:14px;}.chart-tools{gap:7px;}.panel-head small{font-size:8px;}.kicker{font-size:8px;letter-spacing:1px;}}
`;
