'use client';
import { useLocale } from '../LocaleProvider';
const copy:Record<string,[string,string,string]>={
  back:['กลับไปพอร์ต','Back to portfolio','返回作品集'],
  intro:['ทดลองจูน ดูการตอบสนอง แล้วค่อยปรับให้ดีขึ้น','Tune it. See it. Make it better.','调一调，看响应，再改进。'],
  lead:['สามการทดลองแยกกัน พร้อมโมเดลฟิสิกส์ กราฟสด และตัวควบคุมที่ปรับได้ ลองเริ่มจากค่าตั้งต้นแล้วเปลี่ยนทีละค่า','Three separate experiments with physics models, live plots and adjustable controllers. Start with the balanced preset, then change one gain at a time.','三个独立实验，配备物理模型、实时曲线和可调控制器。从平衡预设开始，每次调整一个参数。'],
  educational:['สื่อการเรียนรู้ · ไม่ได้เชื่อมอุปกรณ์จริง','LEARNING SIMULATION · NO HARDWARE CONNECTED','学习仿真 · 未连接真实硬件'],
  motor:['มอเตอร์ DC + Encoder','DC motor + encoder','直流电机 + 编码器'],
  pendulum:['ลูกตุ้มกลับหัว','Inverted pendulum','倒立摆'],
  cart:['รถเข็นติดลูกตุ้ม','Cart-pole','小车倒立摆'],
  motorSub:['ความเร็ว / ระยะทาง','SPEED / TRAVEL','速度 / 行程'],
  pendulumSub:['แรงบิดที่จุดหมุน','TORQUE AT THE PIVOT','转轴力矩控制'],
  cartSub:['ตำแหน่ง / การทรงตัว','POSITION / BALANCE','位置 / 平衡'],
  experiment:['เลือกการทดลอง','Choose experiment','选择实验'],
  liveModel:['โต๊ะทดลอง','The test bench','实验台'],
  physicsModel:['จำลองฟิสิกส์','PHYSICS SIMULATION','物理仿真'],
  start:['เริ่มทดลอง','Start experiment','开始实验'],
  pause:['พักการทดลอง','Pause','暂停'],
  reset:['เริ่มใหม่','Reset run','重置实验'],
  nudgeLeft:['รบกวน −','Nudge −','扰动 −'],
  nudgeRight:['รบกวน +','Nudge +','扰动 +'],
  simTime:['เวลาจำลอง','SIM TIME','仿真时间'],
  target:['เป้าหมาย','Target','目标'],
  actual:['ค่าที่วัด','Measured','测量值'],
  error:['คลาดเคลื่อน','Error','误差'],
  effort:['สัญญาณควบคุม','Control effort','控制输出'],
  response:['กราฟการตอบสนอง','Response trace','响应曲线'],
  targetLine:['เป้าหมาย / คำสั่ง','Target / reference','目标 / 参考值'],
  recorded:['รอบที่บันทึก','Saved run','已保存曲线'],
  saveRun:['เก็บกราฟเทียบ','Keep this trace','保存曲线对比'],
  clearSaved:['ลบกราฟเทียบ','Clear comparison','清除对比'],
  export:['ดาวน์โหลด CSV','Export CSV','导出 CSV'],
  lastMinute:['เก็บข้อมูลล่าสุด 60 วินาที','Latest 60 s retained','保留最近 60 秒数据'],
  chartEmpty:['กดเริ่มทดลองเพื่อดูกราฟ','Start the experiment to see a trace','开始实验以查看曲线'],
  tracking:['การติดตามเป้าหมาย','Target tracking','目标跟踪'],
  speedTrace:['ความเร็ว / RPM','Speed / RPM','转速 / RPM'],
  angleTrace:['มุม / องศา','Angle / degrees','角度 / 度'],
  window:['ช่วงเวลาบนกราฟ','Graph time window','曲线时间范围'],
  command:['ตั้งเป้าหมาย','Set a target','设定目标'],
  speedMode:['หมุนต่อเนื่อง','Continuous speed','连续转速'],
  positionMode:['ระยะทาง + ความเร็ว','Travel + speed','行程 + 转速'],
  distance:['ตำแหน่งจากจุดเริ่ม (m)','Position from start (m)','相对起点位置 (m)'],
  rpm:['ความเร็ว (RPM)','Speed (RPM)','转速 (RPM)'],
  maxRPM:['จำกัดความเร็ว (RPM)','Speed cap (RPM)','转速上限 (RPM)'],
  angleCommand:['มุมเป้าหมาย (°)','Target angle (°)','目标角度 (°)'],
  cartCommand:['ตำแหน่งรถเข็น (m)','Cart target (m)','小车目标位置 (m)'],
  apply:['ใช้เป้าหมายนี้','Apply target','应用目标'],
  speedHelp:['หมุนต่อเนื่องตาม RPM ที่ตั้ง ค่าเป็นลบคือหมุนกลับทิศ กดพักเพื่อหยุดเวลาจำลอง','Runs continuously at the requested RPM. Negative values reverse direction. Pause freezes simulation time.','按设定转速持续旋转，负值表示反转。暂停会冻结仿真时间。'],
  positionHelp:['ระยะอ้างอิงจากจุดเริ่มของรอบนี้ ใช้ล้อรัศมี 30 mm แปลงมุมเพลาเป็นระยะ วงตำแหน่งจะลดความเร็วเมื่อเข้าใกล้เป้าหมาย','Absolute travel from this run’s origin. A 30 mm radius wheel converts shaft angle to distance. The outer loop slows the motor near the target.','行程以本次实验起点为零。半径 30 mm 的轮将轴转角换算为距离，位置环在接近目标时降低转速。'],
  pendulumHelp:['0° คือตั้งตรง มุมบวกเอนไปทางขวา เริ่มจากใกล้แนวตั้ง ทดลองแรงรบกวนเพื่อดูว่ากลับมาทรงตัวได้ไหม','0° is upright; positive angles lean right. Start near vertical and nudge the pendulum to test recovery.','0° 为竖直向上，正角度向右倾。从接近竖直处开始，施加扰动测试恢复能力。'],
  cartHelp:['รถเข็นต้องรักษาสมดุลพร้อมไปยังตำแหน่งที่กำหนด อาจขยับย้อนก่อนเพื่อสร้างมุมเอียง รางมีขอบ ±1.2 m','The cart balances the pole while moving to its target. It may move the other way first to create a lean. Rail limits are ±1.2 m.','小车在移动到目标位置时保持摆杆平衡，可能先反向移动以建立倾角。轨道限位为 ±1.2 m。'],
  tune:['จูนตัวควบคุม','Tune the controller','调整控制器'],
  speedLoop:['PID วงความเร็ว','Speed-loop PID','速度环 PID'],
  angleLoop:['PID วงมุม','Angle-loop PID','角度环 PID'],
  outerLoop:['วงตำแหน่งเพิ่มเติม','Outer position loop','外部位置环'],
  motorOuter:['วงตำแหน่งส่งความเร็วอ้างอิงให้วงความเร็ว หน่วย P/I/D คือ (rad/s)/m, rad/(m·s²), rad/m','Position PID supplies the speed reference. P/I/D units: (rad/s)/m, rad/(m·s²), rad/m.','位置 PID 输出转速参考。P/I/D 单位：(rad/s)/m、rad/(m·s²)、rad/m。'],
  cartOuter:['วงตำแหน่งส่งมุมอ้างอิง จำกัด ±12° วงมุมจะสั่งแรงรถเข็น เครื่องหมายแรงกลับด้านตามฟิสิกส์ของระบบ','Position PID requests an angle capped at ±12°. The angle loop commands cart force with the sign required by the cart-pole dynamics.','位置 PID 输出限于 ±12° 的角度参考，角度环按小车倒立摆动力学所需的符号输出推力。'],
  balanced:['ค่าตั้งต้น','Balanced','平衡预设'],
  pOnly:['ลอง P อย่างเดียว','P only','仅 P 控制'],
  noControl:['ปิด PID','PID off','关闭 PID'],
  presetNote:['การเลือกชุดค่าจะเริ่มรอบทดลองใหม่','Choosing a preset resets this experiment.','选择预设将重置当前实验。'],
  proportional:['ตอบสนองต่อข้อผิดพลาด','Present error','当前误差'],
  integral:['ชดเชยที่ค้างอยู่','Accumulated error','累积误差'],
  derivative:['ลดการแกว่ง','Damping','抑制振荡'],
  liveGains:['ปรับค่าได้ขณะกำลังทดลอง','Gains update while the experiment runs.','实验运行中也可调整增益。'],
  motorUnits:['หน่วย P: V/(rad/s) · I: V/rad · D: V·s²/rad','P: V/(rad/s) · I: V/rad · D: V·s²/rad','P: V/(rad/s) · I: V/rad · D: V·s²/rad'],
  pendulumUnits:['หน่วย P: N·m/rad · I: N·m/(rad·s) · D: N·m·s/rad','P: N·m/rad · I: N·m/(rad·s) · D: N·m·s/rad','P: N·m/rad · I: N·m/(rad·s) · D: N·m·s/rad'],
  cartUnits:['หน่วย P: N/rad · I: N/(rad·s) · D: N·s/rad','P: N/rad · I: N/(rad·s) · D: N·s/rad','P: N/rad · I: N/(rad·s) · D: N·s/rad'],
  safeguards:['ตัวเลือก PID','PID options','PID 选项'],
  antiWindup:['กันค่า I สะสมเมื่ออิ่มตัว','Anti-windup','积分抗饱和'],
  derivativeFilter:['ตัวกรอง D (s)','D filter (s)','D 滤波时间 (s)'],
  safeguardHelp:['D ใช้อัตราการเปลี่ยนของค่าที่วัด พร้อมตัวกรองเพื่อลดสัญญาณกระชาก Anti-windup หยุดสะสม I เมื่อสั่งเกินขีดจำกัด','D acts on filtered measurement rate. Anti-windup stops the integral growing further into actuator saturation.','D 作用于滤波后的测量变化率。抗饱和功能防止执行器饱和时积分继续增大。'],
  system:['ปรับแบบจำลอง','Plant parameters','模型参数'],
  systemNote:['การเปลี่ยนค่าทางกายภาพจะพักและเริ่มรอบใหม่ เพื่อเทียบผลได้ชัดเจน','Changing physical parameters pauses and resets the run for a clean comparison.','改变物理参数将暂停并重置实验，便于清晰对比。'],
  voltage:['แรงดันสูงสุด (V)','Voltage limit (V)','电压上限 (V)'],
  torque:['แรงบิดสูงสุด (N·m)','Torque limit (N·m)','力矩上限 (N·m)'],
  force:['แรงสูงสุด (N)','Force limit (N)','推力上限 (N)'],
  mass:['มวลลูกตุ้ม (kg)','Bob mass (kg)','摆锤质量 (kg)'],
  length:['ความยาวลูกตุ้ม (m)','Pendulum length (m)','摆长 (m)'],
  friction:['แรงเสียดทานหนืด b','Viscous friction b','黏性阻尼 b'],
  initialAngle:['มุมเริ่มต้น (°)','Initial angle (°)','初始角度 (°)'],
  load:['แรงบิดภายนอก (N·m)','External load (N·m)','外部负载力矩 (N·m)'],
  encoder:['Encoder (counts/rev)','Encoder (counts/rev)','编码器 (计数/转)'],
  encoderHelp:['นับขอบที่ถอดรหัสแล้วต่อรอบ ไม่ใช่ PPR คำนวณ RPM จากผลต่างจำนวนพัลส์ทุก 10 ms แล้วกรองค่า','Decoded counts per revolution, not PPR. RPM comes from count differences every 10 ms, then filtering.','这里是每转解码后的计数，不是 PPR。每 10 ms 根据计数差计算转速并滤波。'],
  encoderCount:['จำนวนพัลส์สะสม','ENCODER COUNTS','累计编码器计数'],
  countsRev:['counts / รอบ','counts / rev','计数 / 转'],
  uprightAngle:['มุมจากแนวตั้ง','ANGLE FROM UPRIGHT','偏离竖直角度'],
  upright:['ตั้งตรง','upright','竖直向上'],
  shaftCoupled:['มอเตอร์ → encoder → ล้อ','motor → encoder → wheel','电机 → 编码器 → 轮'],
  targetGuide:['แนวเป้าหมายสีส้ม','amber reference guide','橙色目标参考'],
  motorModel:['โมเดลมอเตอร์ DC เพลา encoder และล้อ','DC motor, shaft encoder and wheel model','直流电机、轴编码器与轮模型'],
  pendulumModel:['โมเดลลูกตุ้มกลับหัวพร้อมแนวอ้างอิง','Inverted pendulum with reference guide','带参考线的倒立摆模型'],
  cartModel:['โมเดลรถเข็นติดลูกตุ้มบนราง','Cart-pole on a limited rail','有限轨道上的小车倒立摆模型'],
  inspectModel:['ซูมดูชิ้นส่วน','Inspect details','放大查看细节'],
  wholeRig:['ดูทั้งชุดทดลอง','View entire rig','查看完整实验装置'],
  dragModel:['โมเดลสำหรับรบกวนระบบด้วยการลาก ใช้การลาก ปากกา หรือปุ่มลูกศร','Model with drag disturbance. Drag, use a pen, or press arrow keys.','可通过拖动施加扰动的模型。可使用拖动、触控笔或方向键。'],
  dragHint:['กดเริ่ม แล้วลากซ้าย–ขวาเพื่อรบกวน · PID จะพยายามฟื้นตัว','Press Start, then drag left/right to disturb · PID will recover','点击开始后左右拖动以施加扰动 · PID 将尝试恢复'],
  modelFallback:['ภาพ 2D · ฟิสิกส์และกราฟยังทำงาน','2D view · physics and plots still active','二维视图 · 物理仿真与曲线仍可用'],
  ready:['พร้อมให้ทดลอง','Ready when you are','准备就绪'],
  readyHelp:['ตั้งเป้าหมายแล้วกดเริ่มทดลอง ค่าตั้งต้นเป็นจุดเริ่มสำหรับแบบจำลองนี้','Set a target and press Start. The preset is a starting point for this model.','设定目标后点击开始。预设值适用于当前模型的初步实验。'],
  running:['กำลังติดตามเป้าหมาย','Tracking the reference','正在跟踪目标'],
  runningHelp:['ดูเส้นค่าที่วัดเทียบกับเส้นเป้าหมาย ลองปรับทีละค่าแล้วสังเกตการแกว่งและเวลาที่ใช้','Compare the measured and reference traces. Change one gain at a time and watch the oscillation and response time.','比较测量曲线与参考曲线。每次调整一个参数，观察振荡和响应时间。'],
  settled:['อยู่ในช่วงเป้าหมาย','Inside the target band','处于目标范围内'],
  settledHelp:['สถานะนี้อิงค่าปัจจุบันและช่วงเวลาที่อยู่ในเกณฑ์ ไม่ใช่การรับประกันเสถียรภาพทุกสภาวะ','This indicates recent tracking within tolerance, not guaranteed stability under every condition.','此状态表示近期跟踪误差在容差内，并不保证所有工况下都稳定。'],
  saturated:['สั่งถึงขีดจำกัดแล้ว','Actuator at its limit','执行器达到限幅'],
  saturatedHelp:['การเพิ่ม P หรือ I อาจไม่ช่วยให้เร็วขึ้น ลองลดเป้าหมายหรือตรวจขีดจำกัดแรง/แรงดัน และเปิด anti-windup','More P or I may not make it faster. Reduce the target or review the force/voltage limit, and enable anti-windup.','继续增大 P 或 I 不一定更快。可减小目标、检查力或电压上限，并开启抗饱和。'],
  unreachable:['ความเร็วเกินกำลังแบบจำลอง','Requested speed exceeds no-load capability','目标转速超过模型空载能力'],
  unreachableHelp:['ค่าสูงสุดโดยประมาณจากแรงดันและค่ามอเตอร์ต่ำกว่า RPM ที่สั่ง ลองลดความเร็วหรือเพิ่มแรงดันในแบบจำลอง','The model’s estimated no-load speed is below the command. Lower the RPM or increase the model voltage limit.','模型估算的空载转速低于指令值。请降低转速或提高模型电压上限。'],
  fallen:['ลูกตุ้มล้มแล้ว','Pendulum fell','摆杆已倒下'],
  fallenHelp:['มุมเกิน 80° จึงหยุดรอบนี้ กดเริ่มใหม่และลองเพิ่ม P/D หรือเริ่มจากมุมที่เล็กลง ระบบนี้ฝึกทรงตัวใกล้แนวตั้ง ไม่ได้ทำ swing-up','The angle exceeded 80°, so this run stopped. Reset and try more P/D or a smaller initial angle. This lab balances near upright; it does not perform swing-up.','角度超过 80°，本次实验已停止。重置后尝试增加 P/D 或减小初始角度。本实验只在竖直附近保持平衡，不执行起摆。'],
  rail:['รถเข็นถึงขอบราง','Rail limit reached','到达轨道限位'],
  railHelp:['รถเข็นถึง ±1.2 m รอบนี้หยุดโดยไม่เด้งกลับ กดเริ่มใหม่ แล้วลดเป้าหมายหรือปรับวงตำแหน่งร่วมกับวงมุม','The cart reached ±1.2 m. The run stops without a simulated bounce. Reset, reduce travel, or tune position and angle loops together.','小车到达 ±1.2 m，实验停止且不模拟反弹。请重置、缩短行程或共同调整位置环与角度环。'],
  numeric:['ค่าการจำลองออกนอกขอบเขต','Simulation exceeded numerical limits','仿真超出数值范围'],
  numericHelp:['หยุดคำนวณแล้ว ลองใช้ค่าตั้งต้นและลดความรุนแรงของตัวควบคุม','Calculation stopped. Restore the balanced preset and reduce aggressive gains.','计算已停止。请恢复平衡预设并降低过大的增益。'],
  off:['PID ถูกปิด','PID is off','PID 已关闭'],
  offHelp:['P, I และ D เป็นศูนย์ ระบบจะตอบสนองตามแรงเฉื่อย แรงโน้มถ่วง และแรงเสียดทาน','P, I and D are zero. Motion follows inertia, gravity and friction.','P、I、D 均为零，系统按惯性、重力和摩擦运动。'],
  paused:['พักการทดลอง','Experiment paused','实验已暂停'],
  pausedHelp:['เวลาและกราฟหยุดอยู่ที่จุดนี้ ปรับค่าแล้วกดเริ่มเพื่อทดลองต่อ หรือเริ่มใหม่เพื่อล้างรอบ','Time and plots are frozen. Change gains and resume, or reset for a fresh run.','时间与曲线停在此处。可以调整增益后继续，或重置开始新实验。'],
  pausedTab:['พักเมื่อสลับแท็บ กดเริ่มเพื่อทดลองต่อ','Paused while the tab was hidden. Press Start to continue.','切换到后台时已暂停，点击开始继续。'],
  commandApplied:['ใช้เป้าหมายใหม่แล้ว','New target applied','已应用新目标'],
  pointerDisturb:['เพิ่มแรงรบกวนจากการลากแล้ว','Drag disturbance applied','已施加拖动扰动'],
  pointerDisturbHelp:['แรงกระตุกถูกเติมเข้าสู่สถานะจริงของแบบจำลอง โดยไม่เปลี่ยนเป้าหมาย ดูการฟื้นตัวบนกราฟ','The impulse was added to the physical state without changing the target. Watch recovery on the plot.','冲量已施加到模型物理状态，不改变目标。请观察曲线恢复。'],
  startBeforeDrag:['กดเริ่มทดลองก่อน แล้วจึงลากเพื่อรบกวน','Start the experiment before dragging a disturbance','请先开始实验，再拖动施加扰动'],
  startBeforeDragHelp:['ค่าเริ่มต้นและเป้าหมายตั้งจากช่องควบคุม การลากใช้เพื่อทดสอบการฟื้นตัวของ PID ระหว่างรัน','Set initial conditions and targets in the controls. Drag tests PID recovery while running.','初始条件和目标由控制面板设定。拖动用于在运行中测试 PID 恢复。'],
  disturbed:['เพิ่มแรงรบกวนแล้ว ดูการฟื้นตัวบนกราฟ','Disturbance applied. Watch the recovery.','已施加扰动，请观察恢复过程。'],
  savedRun:['เก็บกราฟแล้ว เริ่มรอบใหม่เพื่อเทียบการจูน','Trace saved. Reset and run again to compare tuning.','已保存曲线，重置后重新运行以比较调参效果。'],
  invalidCommand:['กรอกเป้าหมายให้อยู่ในช่วงที่กำหนด และใช้ความเร็วมากกว่า 0 ในโหมดระยะทาง','Enter a target within range. Travel mode needs a positive speed cap.','请输入范围内的目标，行程模式的转速上限必须大于零。'],
  learn1:['เริ่มจาก P แล้วดูการแกว่ง','Start with P. Watch the motion.','从 P 开始，观察运动。'],
  learn1Body:['P ช่วยตอบสนองต่อความคลาดเคลื่อน แต่เพิ่มมากไปอาจแกว่งหรือชนขีดจำกัด ลูกตุ้มกลับหัวต้องมีแรงควบคุมพอเอาชนะแรงโน้มถ่วง','P reacts to present error. Too much can cause oscillation or saturation. An inverted pendulum needs enough control authority to counter gravity.','P 对当前误差作出响应，过大会引起振荡或饱和。倒立摆需要足够的控制能力来克服重力。'],
  learn2:['ใช้ D ช่วยหยุดให้พอดี','Use D to damp the response.','用 D 抑制振荡。'],
  learn2Body:['D ช่วยต้านการเปลี่ยนที่เร็วเกินไป ดูว่าลดการแกว่งได้หรือไม่ หาก encoder หยาบ ค่า D สูงจะไวต่อการกระโดดของค่าที่วัด','D resists fast changes. Watch whether it reduces oscillation. With coarse encoder resolution, a high D gain is sensitive to measurement steps.','D 抑制过快变化，观察是否减少振荡。编码器分辨率较低时，较大 D 对测量跳变更敏感。'],
  learn3:['เติม I เมื่อยังคลาดเคลื่อน','Add I for persistent error.','用 I 消除持续误差。'],
  learn3Body:['I ชดเชยความคลาดเคลื่อนที่ค้างอยู่ เช่น แรงบิดโหลดหรือแรงโน้มถ่วง เริ่มจากน้อย ๆ เปิด anti-windup และเทียบกราฟก่อน–หลัง','I compensates persistent error from load torque or gravity. Start small, use anti-windup, and compare saved traces.','I 补偿负载力矩或重力造成的持续误差。先使用较小值，开启抗饱和并比较保存的曲线。'],
  assumptions:['สมการ ขอบเขต และที่มาของแบบจำลอง','Equations, assumptions & model sources','方程、假设与模型来源'],
  modelScope:['ใช้ฟิสิกส์ไม่เชิงเส้นและหน่วย SI คำนวณ RK4 ทุก 2 ms ควบคุมทุก 10 ms ลูกตุ้มเป็นมวลที่ปลายก้านไร้มวล กราฟกับโมเดลใช้สถานะเดียวกัน ค่าพารามิเตอร์เป็นตัวอย่าง ไม่ได้สอบเทียบกับฮาร์ดแวร์รุ่นใด','Nonlinear SI models use RK4 at 2 ms and control at 10 ms. Pendulums are point masses on massless rods. Plots and models share the same state. Example parameters are not calibrated to a particular hardware product.','非线性 SI 模型使用 2 ms RK4 积分和 10 ms 控制周期。摆为无质量杆末端的质点。曲线与模型共享状态，示例参数未对特定硬件产品进行标定。'],
  band:['เกณฑ์: ความเร็ว ±3% หรือ 5 RPM, ระยะมอเตอร์ ±5 mm, มุม ±1°, รถเข็น ±20 mm และมุม ±1° ต้องอยู่ในช่วงนาน 1 วินาที','Band: speed ±3% or 5 RPM; motor travel ±5 mm; angle ±1°; cart position ±20 mm and angle ±1°. Must remain inside for 1 s.','容差：转速 ±3% 或 5 RPM，电机行程 ±5 mm，角度 ±1°，小车位置 ±20 mm 且角度 ±1°。需连续保持 1 秒。'],
  footer:['ทดลองเพื่อเข้าใจ ไม่ใช่ค่าจูนสำเร็จสำหรับอุปกรณ์จริง','Learn the behavior; these are not ready-to-deploy hardware gains.','用于理解系统行为，并非可直接用于实物的整定参数。'],
};
export function usePIDText(){const{locale}=useLocale();return(key:string)=>copy[key]?.[locale==='th'?0:locale==='en'?1:2]??key;}
